#!/bin/bash
##
## renew-root-ca-crl.sh - refresh the root CA CRL and optionally publish it
##

set -euo pipefail

BASE=$(realpath "$(dirname "$0")")
cd "${BASE}" || exit 1

# Local CRL path (generated by gen-root-ca-crl.sh)
CRL_PATH="${BASE}/CRL/root-ca.crl.pem"

# Optional remote publish target (edit to match your environment)
REMOTE_USER="root"
REMOTE_HOST="mail"     # replace with your mail server hostname/IP
REMOTE_PATH="/etc/mail/certs/root-ca.crl.pem"
REMOTE_RESTART_CMD="/etc/rc.d/rc.sendmail restart"  # or: systemctl restart sendmail

usage() {
  echo "Usage: $0 [--publish] [--restart]"
  echo "  --publish  Upload CRL to remote target via scp"
  echo "  --restart  Also restart remote mail service after upload"
}

PUBLISH=false
RESTART=false
while [[ ${1:-} ]]; do
  case "$1" in
    --publish) PUBLISH=true ;;
    --restart) RESTART=true ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown option: $1"; usage; exit 1 ;;
  esac
  shift || true
done

echo "[INFO] Generating CRL via gen-root-ca-crl.sh"
"${BASE}/gen-root-ca-crl.sh"

if [[ ! -f "${CRL_PATH}" ]]; then
  echo "[ERROR] Expected CRL not found at ${CRL_PATH}"
  exit 1
fi

if ${PUBLISH}; then
  if ! command -v scp >/dev/null 2>&1; then
    echo "[ERROR] scp not found in PATH"
    exit 1
  fi
  echo "[INFO] Publishing CRL to ${REMOTE_USER}@${REMOTE_HOST}:${REMOTE_PATH}"
  scp -p "${CRL_PATH}" "${REMOTE_USER}@${REMOTE_HOST}:${REMOTE_PATH}"

  if ${RESTART}; then
    if ! command -v ssh >/dev/null 2>&1; then
      echo "[ERROR] ssh not found in PATH"
      exit 1
    fi
    echo "[INFO] Restarting remote service on ${REMOTE_HOST}"
    if ! ssh -o BatchMode=yes "${REMOTE_USER}@${REMOTE_HOST}" "${REMOTE_RESTART_CMD}"; then
      echo "[WARN] Remote restart failed; please check manually."
    fi
  fi
else
  echo "[INFO] Skipping publish (use --publish to upload)."
fi

echo "[INFO] Done."